### PR TITLE
dark mode added✨

### LINKED ISSUE #54: [FEAT] adding Darkmode feature✨
A dark mode feature can improve user experience.

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

https://github.com/user-attachments/assets/4297699c-6378-46db-8388-7c093a3fc7dd

closes #54 

### Type of Change
- [ ] Bug fix
- [X] New feature
- [ ] Documentation update
- [X] Refactoring
- [ ] Other (please describe):

### Checklist
- [X] I have tested my changes and ensured they work as expected.
- [X] I have added necessary documentation (if applicable).
- [X] I have reviewed my code for style and linting issues.
- [X] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Vimall03 its nice right , can i get level 2 😁

**Comment by T-Rahul-prabhu-38** [comment]
its working on all

**Comment by T-Rahul-prabhu-38** [comment]
@Vimall03 do review this, thank you.

**Comment by Vimall03** [comment]
Hey @T-Rahul-prabhu-38 there are a few flaws that I see. In some cases the text color is behaving weirdly. as you can see in the  image - 
image
image

And I don't see the dark mode work after I sign in. So it doesn't work in all the pages. 

I expect you to fix this in the PR for your current issue #56. If this is fixed i can change this PR to level 2.

**Comment by T-Rahul-prabhu-38** [comment]
sureee ill fix that right away .

**Comment by T-Rahul-prabhu-38** [comment]
@Vimall03 ive tried to fix the dark mode for all , but i have never worked with php and i dont thnk ill be able to do it.
i understand the deal was level 2 only if i solve it but if u liked the home page can u make this level2 back please.
Thank you

**Pull request merged**
