### PR TITLE
Redesigned landing page

### PR DESCRIPTION
**Pull request by ArchanRD**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Description of Changes
A complete new design of landing page. Includes redesign of navbar. 

### Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

### Related Issue
Closes: #110 

### Testing
Testing for following has been done
1. Responsiveness
2. Working links in navbar
3. Hamburger menu in small screen

### Checklist
- [x] I have tested my changes and ensured they work as expected.
- [x] I have added necessary documentation (if applicable).
- [x] I have reviewed my code for style and linting issues.
- [x] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Comment by ArchanRD** [comment]
@Vimall03 There is merge conflict which cannot be resolved by me as the button is disabled. The conflict is because I have completed removed index.html file. Which is here replaced with index.php

**Review by Vimall03 — APPROVED** [review]

**Comment by Vimall03** [comment]
@ArchanRD There is a conflict on the PR, Please fix it

**Comment by ArchanRD** [comment]
@Vimall03 Please check it now! It is resolved.

**Comment by Vimall03** [comment]
okay @ArchanRD, I'll assign the labels once I review the code

**Comment by Vimall03** [comment]
@ArchanRD I have opened a new issue #136. comment under that issue if you are interested i will push it to level 3

**Comment by ArchanRD** [comment]
@Vimall03 I would really love to work on this but this week I am having some important work to do, so would not be able to focus on such big issues!

**Comment by Vimall03** [comment]
Cool, no worries

**Pull request merged**
