### PR TITLE
changed navbar design

### LINKED ISSUE #109: [FEAT] Redesign & Fix NavBar in all the pages.
There is a inconsistency in Navbar design throughout the site. We need to implement a standard Navbar with broken link fixes. 
This is a level 2 issue, So the design and implementation needs to be visually appealing and userfriendly 

**Screenshot of some inconsistent navbars :**

image

image

image

Comment on this issue if you are interested in contributing.

### PR DESCRIPTION
**Pull request by Sourabh782**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:
Closes #109 
### Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [X] Refactoring
- [ ] Other (please describe):

### Related Issue

Closes: #109 

### Checklist
- [X] I have tested my changes and ensured they work as expected.
- [X] I have added necessary documentation (if applicable).
- [X] I have reviewed my code for style and linting issues.
- [X] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Review by Vimall03 — APPROVED** [review]

**Comment by Sourabh782** [comment]
> @Sourabh782, I'm pulling this issue back to level 1. There were a lot of UI bugs that came in with this PR. There was improper rendering of restaurants and cart items in home.php and menu.php along with a few more bugs as well. I have reverted this PR. I'm sorry i wont be able to give this PR level 2. Thankyou for understanding.

Sir the main reason is like we are using all bootstrap, tailwind and custom css, so all three are conflicting with each other

**Comment by Vimall03** [comment]
Which one did you use to build it ?

**Comment by Sourabh782** [comment]
> Which one did you use to build it ?

For navbar I used tailwind

**Comment by Vimall03** [comment]
Oh then that shouldn't have been an issue, Anyways the tailwind is already setup in the project so use I believe you can use it directly without any configuration. Please make sure you do that with your upcoming PRs

**Comment by Sourabh782** [comment]
Yes

> Oh then that shouldn't have been an issue, Anyways the tailwind is already setup in the project so use I believe you can use it directly without any configuration. Please make sure you do that with your upcoming PRs

Yes also I haven't removed any code just commented the css linking refs, but the conflicts are still there between css files, tailwind and bootstrap

**Comment by Vimall03** [comment]
No worries

**Pull request merged**
