### PR TITLE
Update homemadedb.sql

### PR DESCRIPTION
**Pull request by Anushka-Pote**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Description of Changes
Introduced a loyalty points system to reward users based on their order spending, which encourages repeat business and enhances customer retention.
Database Changes
New Table: user_points table to store user points data.
Trigger: award_points_after_order to update points in user_points based on order amount.

Open Source- Hacktoberfest and GSSOC-Ext

### Type of Change
- [] Bug fix
- [X] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

### Related Issue
Closes: #173 

### Testing
It can be checked in the database only, nothing in the frontend working session.

### Checklist
- [ ] I have tested my changes and ensured they work as expected.
- [x] I have added necessary documentation (if applicable).
- [] I have reviewed my code for style and linting issues.
- [x] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Comment by Vimall03** [comment]
@Anushka-Pote I see you have only made changes to the database schema. This adds nothing to the project since it technically doesn't work. I wont be able to merge this PR until the points are updated based on the orders as mentioned in your issue

**Comment by Anushka-Pote** [comment]
Makes sense 
Actually I am not very friendly with PHP yet so that's why I will need some more time for this, but I will try to get it done as per the issue

**Comment by Anushka-Pote** [comment]
Yeah Cool
Fine by me, I am trying to work with PHP so in case for any improvement, I will get another issue or PR 
That would be best for both

**Comment by Vimall03** [comment]
Great! Thank you for your efforts on this project. However, please don’t feel the need to invest excessive time solely for its sake.

Additionally, given current industry trends, PHP has seen reduced usage, so it might be more beneficial to focus on skills that align with emerging technologies.

**Pull request merged**
