### PR TITLE
New track order page

### PR DESCRIPTION
**Pull request by ArchanRD**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Description of Changes
Redesigned the track_order.php page. It is now more approaching in terms of readability and responsiveness. 
Redesigned the navbar considering a part of this page. Ensured for a smooth navigation while redesigning the navbar. Navbar is also responsive.

### Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

### Related Issue

Closes: #96 

### Testing
Following tests have been perfomed:
 - [x] Cannot be accessed without login
 - [x] Fetched all the order from table
 - [x] Redirect to new track order page after payment
 - [x] Responsive across devices  

### Checklist
- [x] I have tested my changes and ensured they work as expected.
- [ ] I have added necessary documentation (if applicable).
- [x] I have reviewed my code for style and linting issues.
- [x] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Review by Vimall03 — APPROVED** [review]

**Comment by Vimall03** [comment]
Hey @ArchanRD, Would you be able to add these columns as well ? 
image

Just the update order column as delivery status and feedback as rating.

**Comment by ArchanRD** [comment]
Yeah sure, I will give it a try. Are you going to create a new issue for this? Or it will be merged through this PR only?

**Comment by Vimall03** [comment]
Cool, There's no need to create a new issue since this is a part of #96, So you can directly open a new PR

**Comment by ArchanRD** [comment]
Hey @Vimall03 I have made the mentioned changes. But it seems the PR or Issue is closed. And I am getting a button to compare & pull request 

image

**Comment by Vimall03** [comment]
Yes, you can click on the compare and pull request to open a new PR.

**Pull request merged**
