### PR TITLE
now the buttons click

### PR DESCRIPTION
**Pull request by GauriSachan**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

### Related Issue

Closes: #55

### Checklist
- [ ] I have tested my changes and ensured they work as expected.
- [ ] I have added necessary documentation (if applicable).
- [ ] I have reviewed my code for style and linting issues.
- [ ] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Comment by Vimall03** [comment]
image

Hey @GauriSachan , I'm not sure what you have done here. Can you explain ?

**Comment by GauriSachan** [comment]
> image
> 
> Hey @GauriSachan , I'm not sure what you have done here. Can you explain ?

@Vimall03 sure earlier the buttons were not clickable and we were not able to submit forms but now we can do so

**Comment by Vimall03** [comment]
I see some UI bug here. You can check the screenshot I have added. 
There is a form that's rendering under the navbar.
Also the contact forum is fixed by one of the contributor, I believe the data is forwarded to an email.

**Comment by GauriSachan** [comment]
> Please fix the rendering of the new forum. Not sure why a new forum is added to the site while the previous one was working.

@Vimall03 done

**Review by Vimall03 — APPROVED** [review]

**Pull request merged**
