### PR TITLE
enhanced vendor ui

### LINKED ISSUE #44: [FEAT] Complete Redesign of Vendor's UI
### Description:
The **vendor's section** of the website requires a **complete UI redesign** to improve appearance, usability, and consistency across all vendor-related pages. There are approximately **four pages** that need to be redesigned, not just the homepage. This is a **level 3 issue**, so please be prepared to fully redesign the UI for all vendor pages.

Contributors are required to first submit a **design proposal (e.g., via Figma)** for review. Based on the design, you will be assigned to proceed with development. The redesign should focus on improving layout, typography, color schemes, and overall user experience.

### Pages to be Redesigned:
1. Vendor Homepage
2. Vendor Dashboard
3. Vendor Restaurant Management Page
4. Vendor Settings Page

### Requirements:
- Apply the redesign to all vendor-related pages.
- Ensure consistency in design across the pages.
- The UI should be clean, user-friendly, and visually appealing.
- You may adjust layout, font size, color schemes, and other stylistic elements to improve the user experience.
- You can use **Bootstrap**, **Tailwind CSS**, or any other frameworks, but ensure all links are functional and no broken links remain.

### Steps to Reproduce:
1. Clone the project and set it up locally. (Refer to the setup section in the README)
2. Navigate to the vendor's login page: `http://localhost/alimento/vendor/vendor_login.php`
3. Use the following credentials to access the vendor page:
   - **Email:** aftereditofficial@gmail.com
   - **Password:** Test@1234
4. Review the current UI across all vendor-related pages and identify areas for improvement.

### Screenshot:
image

### Files Involved:
The relevant files for the vendor’s pages are located in:
`alimento/vendor`

### Notes:
- This is a **level 3 issue**, which requires a complete redesign of all vendor-related pages.
- Before you start, **please share a design** (e.g., via Figma) for approval. Once the design is reviewed and approved, you will be assigned the issue.
- If you'd like to create your own credentials or add a new restaurant, you can sign up via the vendor registration page or use the provided credentials to log in and test the UI changes.
- Feel free to suggest any additional UI/UX improvements.

### PR DESCRIPTION
**Pull request by Sourabh782**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Description of Changes

fixes #44 

### Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [X] Refactoring
- [ ] Other (please describe):

### Related Issue

Closes: #44 

### Checklist
- [X] I have tested my changes and ensured they work as expected.
- [X] I have added necessary documentation (if applicable).
- [X] I have reviewed my code for style and linting issues.
- [X] I have ensured that any dependent changes are merged before this PR.

### Additional Notes

home page:
Screenshot 2024-10-15 185700

add item page:
Screenshot 2024-10-15 190031

edit page:
Screenshot 2024-10-15 185721

Additional changes ** Also resolved bug where logout button was not working properly **

### CODE REVIEW

**Comment by Vimall03** [comment]
image

I'm getting this error when I'm trying to add new menu items. Can you please fix this and open a new PR ?

**Comment by Sourabh782** [comment]
Okk I'll check

> image
> 
> Hey @Sourabh782, I'm getting this error when I'm trying to add new menu items. Can you please fix this and open a new PR ?

Yess I'll check it

**Comment by Sourabh782** [comment]
@Vimall03  which error r u facing? i tried CRUD and its working fine

**Comment by Vimall03** [comment]
Okay, I updated the schema. Now its working fine. Good Work @Sourabh782. 
Thankyou for contributing!

**Comment by Vimall03** [comment]
@Sourabh782, Definitely! Please feel free to open a new issue.

**Pull request merged**
