### PR TITLE
Main

### PR DESCRIPTION
**Pull request by snehas-05**
Issue number #122
This pull request introduces the Customizable Meal Options feature to the Alimento platform, allowing users to tailor their meals according to specific dietary preferences and restrictions, such as vegan, gluten-free, or low-carb options. This enhancement aims to provide a more personalized dining experience for our users.

Changes Made
Database Updates:
Created two new tables: meals and dietary_preferences to store meal information and user preferences.
Created an orders table to save user orders with customizations.

Frontend Updates:
index.php:
Implemented a display of available meals with buttons linking to the customization page.
customize_meal.php:
Developed a user-friendly interface allowing users to select dietary preferences and add custom ingredients.
Included form validation using JavaScript to ensure users provide necessary information before submission.
Backend Logic:

process_order.php:
Handled the form submission to process orders with selected preferences and custom ingredients.
Integrated error handling to manage potential issues during order processing.

Styling:
Created a style.css file to provide consistent styling across pages and enhance the visual appearance of meal options and customization forms.
Included Bootstrap for responsive design and quick styling of components.

JavaScript Enhancements:
Added a script.js file for form validation and user feedback during the customization process.

Benefits
Enhanced User Experience: Users can customize their meals based on dietary needs, leading to a more inclusive platform.
Increased User Satisfaction: Tailored meal options are likely to improve customer satisfaction and loyalty.
Broader Market Reach: Catering to various dietary lifestyles attracts a wider audience, including those with specific dietary restrictions.

### Type of Change
- [ ] Bug fix
- [ ✓] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

### Checklist
- [ ✓] I have tested my changes and ensured they work as expected.
- [✓ ] I have added necessary documentation (if applicable).
- [✓ ] I have reviewed my code for style and linting issues.
- [✓ ] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Comment by Vimall03** [comment]
@snehas-05, have you updated the db schema as well?

**Comment by snehas-05** [comment]
Yes I have uploaded my whole code and made all the necessary changes and combined them in a separate folder for better understanding.

**Comment by Vimall03** [comment]
@snehas-05 I see you have added a sql.php for updating the schema. Instead of that can you export the schema file from your phpmyadmin dashboard and replace it with the current homemade.db file ?

**Comment by snehas-05** [comment]
ok give me some time I will do the required changes and commit them.

**Comment by Vimall03** [comment]
@snehas-05, Have you made the changes ? if yes then please commit the changes and push the code.

**Comment by snehas-05** [comment]
I'm so sorry I was busy the whole day in college. I will definitely do it tomorrow. I hope you will understand.

**Comment by Vimall03** [comment]
No worries, take your time. Please make sure you complete it before the end of gssoc deadlines

**Comment by snehas-05** [comment]
Yes sure

**Comment by snehas-05** [comment]
Hey @Vimall03 I have committed the changes. Do I need to make a new pr?

**Comment by Vimall03** [comment]
@snehas-05, No you don't have to open a new PR. I'll merge this. I'll assign the labels once i finish reviewing the code.

**Review by Vimall03 — APPROVED** [review]

**Comment by Vimall03** [comment]
Hey @snehas-05 Can you share some screen shots of your implementation ?

**Comment by snehas-05** [comment]
I'm so sorry as I can't share screenshots because for that I have to update the whole code of the website on my system and that's very complicated.
But I assure you my code is correct and will definitely work.

**Comment by snehas-05** [comment]
@Vimall03 please provide me with the necessary labels otherwise my points will not be counted

**Comment by Vimall03** [comment]
@snehas-05, I wont be able to assign this any labels since this PR does not have any functionality. The code you have pushed is not relevant to the project until and unless it is functional. I'm sorry, I will revert this PR. Thankyou for understanding.

**Pull request merged**
