### PR TITLE
added forget password para

### PR DESCRIPTION
**Pull request by aditiverma-21**
image

### CODE REVIEW

**Review by Vimall03 — CHANGES_REQUESTED** [review]
Hey @aditiverma-21, I see that you have simply added a paragraph tag for a level 2 issue. Is it possible for you to make the `forgot password ?` link functional ?

**Comment by Vimall03** [comment]
Also, mention the issue you're trying to open a PR for, using # followed by the issue number to reference the issue for clarifications. For example, #4.

**Comment by aditiverma-21** [comment]
> Also, mention the issue you're trying to open a PR for, using # followed by the issue number to reference the issue for clarifications. For example, #4.

Yes sure making more changes with clarity this time.

**Comment by aditiverma-21** [comment]
@Vimall03 Can you Please add level to this PR?

**Comment by Vimall03** [comment]
closes issue #4

**Review by Vimall03 — COMMENTED** [review]
reviewed changes

**Pull request merged**
