### PR TITLE
Added 4 New Files: profile.php, update_profile.php, change_password.php, orders.php and Changed Database Schema

### PR DESCRIPTION
**Pull request by Ashwanisingh7930**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

### Related Issue

Closes: #81

### Testing

I have updated Database Schema so please verify this

### Checklist
- [x] I have tested my changes and ensured they work as expected.
- [x] I have added necessary documentation (if applicable).
- [x] I have reviewed my code for style and linting issues.
- [x] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Review by Vimall03 — APPROVED** [review]
Great Work!

**Comment by Vimall03** [comment]
Hey @Ashwanisingh7930, can you fix these errors in a new PR : 
I might have to revert the changes you made if these errors are not fixed.

image

image

PS: I updated the database schema and created a new account, but still see these errors

**Comment by Ashwanisingh7930** [comment]
Hey @Vimall03 , thanks for reviewing my PR. I apologize for the errors that were introduced. I'll take a closer look and fix them as soon as possible.

**Comment by Ashwanisingh7930** [comment]
Hey @Vimall03,
I've verified that the changes are working correctly on my local machine, but I understand that issues are still present on your end. To resolve this, I propose that we drop all the tables in the current database and import the new database schema that I provided. This should ensure a clean and consistent state.
Screenshot 2024-10-12 172859

**Comment by Vimall03** [comment]
Yes, i have dropped the old database and used the new database schema. Can you try creating a new account and login, This issue is seen only when the new account is logged in for the first time.

**Comment by Ashwanisingh7930** [comment]
Please accept the new PR and then pull the main branch, clean the database, and recreate it using the modified SQL file that I provided earlier. This should ensure a clean and consistent state.
Let me know if the issues are resolved on your end after completing these steps.

**Comment by Vimall03** [comment]
Great the issue is resolved in #93! This is an amazing addition to the project, Thankyou @Ashwanisingh7930

**Pull request merged**
