### PR TITLE
Converted_Images_to_WebP_for_Better_Optimization

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #140 

- Converted all relevant images from formats like PNG and JPEG to WebP for better optimization and performance.
- WebP offers better compression without significant quality loss, which helps in reducing file sizes and improves page load speed.

**Changes:**

- Replaced existing image formats (JPEG, PNG) with WebP versions.
- Updated image references in HTML files to reflect the new WebP file paths.
- Verified that images render correctly in browsers that support WebP.

**Testing:**

- Verified on multiple browsers (Chrome, Firefox, etc.) to ensure proper image rendering.
- Ensured fallback mechanisms are in place for browsers that do not support WebP (if needed).

_**Note**_:  Add gssoc-ext with level3, hacktoberfest-accepted labels!
add level3 because i have done a lot of editing in the files!

@Vimall03

### CODE REVIEW

**Comment by Vimall03** [comment]
@smog-root, I will assign the labels once i review the code

**Comment by smog-root** [comment]
> @smog-root, I will assign the labels once i review the code 
>  


Okay!!

**Comment by smog-root** [comment]
And assign me!!@Vimall03 hey.. add level3 not level2!!

**Comment by Vimall03** [comment]
I've reviewed the PR, and there are a couple of issues. You mentioned implementing lazy loading in the issue, but it’s not there in the code. Please don’t expect to get a level 3 just for switching .png to .webp—that’s not enough.

Also, tone matters when posting in a public forum. Let’s keep things professional.

**Comment by smog-root** [comment]
Okay dude I got you!!

I asked for a lot!!!

**Pull request merged**
