### PR TITLE
Complete Redesign of Client's UI 

### PR DESCRIPTION
**Pull request by SumitSahu44**
## Pull Request Checklist

Thank you for contributing to our project! Please ensure the following before submitting your pull request:

### Description of Changes
Worked on Client's Ui in this PR i did new menu and checkout page with a modern good looking design

**Check this video before merge**
https://github.com/user-attachments/assets/bcb0530f-f4a9-4feb-a3c9-2d5afc7fcfb2

Complete Redesign of Client's UI #43
### Related Issue
Fix issue number #43 

### Testing
Fix database connectivity and login the user and just use it 
### Checklist
- [x] I have tested my changes and ensured they work as expected.
- [x] I have added necessary documentation (if applicable).
- [x] I have reviewed my code for style and linting issues.
- [x] I have ensured that any dependent changes are merged before this PR.

### CODE REVIEW

**Review by Vimall03 — APPROVED** [review]

**Comment by SumitSahu44** [comment]
hey @Vimall03 assign me and add label their are no any label
image

**Comment by Vimall03** [comment]
@SumitSahu44, The UI looks great. The checkout Forms looks good as well. Good work!

**Comment by SumitSahu44** [comment]
Thanks @Vimall03 ready to work next issue

**Comment by Vimall03** [comment]
> Thanks @Vimall03 ready to work next issue

Happy to know, Please open a new issue if you feel like something needs a fix or comment on existing issues to assign them to you.

**Comment by SumitSahu44** [comment]
hey @Vimall03 is there ant issue you have which is level 2 or 3 so i can work on it

**Pull request merged**
